id: A6F89766F
title: 'Clouds to Delight Amitābha, Melody of the Realm of Great Bliss: Aspiration
  and Auspicious Verses for the Spread of the Teachings of the Lake-Born Vajra of
  Oḍḍiyāna, Second Teacher of this World'
type: translation
pechas:
- I2739F747
- I9BB63EAC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:03.735709
  last_modified_at: 2023-01-04 12:07:03.735717
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I2739F747/101A: B03B
  I9BB63EAC/795E: B03B
